/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 model.gltf --transform
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-star-star-wars-699e5f635f7a4b21a4c0d2e3f5b68324
Title: Death Star (Star Wars)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model-transformed.glb')
  // const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Death_StarFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Death_Star" position={[0, 0, 0]} rotation={[-2.18, 0.05, 0.02]} scale={3.58}>
                  <group name="Object_5" rotation={[0.61, -0.05, 0.02]}>
                    <mesh name="Death_Star_03_-_Default_0" geometry={nodes['Death_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                    <mesh name="Death_Star_02_-_Default_0" geometry={nodes['Death_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                    <mesh name="Death_Star_07_-_Default_0" geometry={nodes['Death_Star_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
